version: '3.3'

services:
  reverse-proxy-blue-node-api:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue-node-api
    
  blue-node-api:
    image: blue-node-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: blue-node-container
    restart: unless-stopped